;;; -*- lexical-binding: t -*-
(add-to-list 'load-path "/workspace/org-incremental-writing")
(require 'org-iw-discovery)
(defmacro tm (label &rest body)
  `(let ((t0 (float-time)))
     (prog1 (progn ,@body)
       (princ (format "%-40s %.2fs\n" ,label (- (float-time) t0))))))
(let ((files (org-iw-discovery-files (list "/tmp/iw/j") nil)))
  (tm "insert only" (dolist (f files) (with-temp-buffer (insert-file-contents f))))
  (tm "insert+org-mode" (dolist (f files) (with-temp-buffer (insert-file-contents f) (delay-mode-hooks (org-mode)))))
  (tm "insert+org-mode+scan-buffer" (dolist (f files) (with-temp-buffer (insert-file-contents f) (delay-mode-hooks (org-mode)) (org-iw-discovery--scan-buffer f))))
  (require 'profiler)
  (profiler-start 'cpu)
  (org-iw-discovery-scan files)
  (profiler-stop)
  (with-current-buffer (profiler-report-profile-other-window (profiler-cpu-profile))
    (profiler-report-expand-all)
    (princ (buffer-substring-no-properties (point-min) (min (point-max) 6000)))))
