;;; -*- lexical-binding: t -*-
(add-to-list 'load-path "/workspace/org-incremental-writing")
(require 'org-iw-discovery) (require 'org-iw-write) (require 'org-id)
(setq org-id-locations-file "/tmp/iw/ids2" org-id-track-globally t)
(defmacro tm (label &rest body)
  `(let ((t0 (float-time)))
     (prog1 (progn ,@body)
       (princ (format "%-40s %.2fs\n" ,label (- (float-time) t0))))))
(let* ((dir (car command-line-args-left))
       (files (tm "select files" (org-iw-discovery-files (list dir) nil))))
  (princ (format "%d files, emacs %s\n" (length files) emacs-version))
  (tm "scan, no members" (org-iw-discovery-scan files))
  (let ((rank 0) (opened 0))
    (tm "batch write (visit+put+save+kill)"
        (dolist (f files)
          (let* ((had (find-buffer-visiting f))
                 (buf (org-iw-discovery-buffer f)))
            (unless had (cl-incf opened))
            (cl-incf rank 1024)
            (org-iw-write-put-rank (with-current-buffer buf (copy-marker (point-min)))
                                   "J" rank :expected :absent :ensure-id t)
            (unless had (kill-buffer buf)))))
    (princ (format "opened %d\n" opened)))
  (garbage-collect)
  (let ((scan (tm "scan, all members" (org-iw-discovery-scan files))))
    (princ (format "entries %d problems %d\n" (length (org-iw-scan-entries scan))
                   (length (org-iw-scan-problems scan))))
    (tm "scan, all members (2nd)" (org-iw-discovery-scan files))))
