;;; -*- lexical-binding: t -*-
(require 'org) (require 'org-id)
(setq org-id-locations-file "/tmp/iw/ids")
(defun probe (name text)
  (let ((f (make-temp-file "iw" nil ".org" text)))
    (with-current-buffer (find-file-noselect f)
      (goto-char (point-max))
      (org-with-point-at (point-min) (org-id-get-create))
      (org-entry-put (point-min) "IW_J" "1024")
      (princ (format "---- %s\n%s\n" name (buffer-string))))))
(princ (format "org %s emacs %s\n" org-version emacs-version))
(probe "bare title" "#+title: Journal\n\nSome text.\n* H1\n")
(probe "comments+title" "# -*- mode: org -*-\n#+title: Journal\n#+filetags: :x:\n\nText\n")
(probe "existing drawer" ":PROPERTIES:\n:ID: abc\n:END:\n#+title: T\n\nText\n* H\n")
(probe "empty file" "")
(probe "heading first" "* H1\nbody\n")
(probe "blank then text" "\n\nhello\n")
