(require 'org) (require 'org-id)
(message "emacs %s org %s" emacs-version (org-version))
(message "sort-kw: %S value<: %S" (condition-case e (sort '(3 1 2) :key #'identity) (error e)) (fboundp 'value<))
(message "bignum: %S fixnump-big: %S" (* most-positive-fixnum 4) (fixnump (* most-positive-fixnum 4)))
(message "pkg-lint: %S" (locate-library "package-lint"))
(message "checkdoc: %S" (locate-library "checkdoc"))
(let ((f (make-temp-file "iw" nil ".org" ":PROPERTIES:\n:ID:       doc-id\n:IW_ESSAYS: 3584\n:IW_AFTER_ESSAYS: 99\n:END:\n#+title: Doc\n\n* H1\n:PROPERTIES:\n:ID: h1\n:IW_ESSAYS: 5120\n:END:\n** H1a\nbody\n* H2\n")))
  (with-current-buffer (find-file-noselect f)
    (goto-char (point-min))
    (message "doc-level get: %S / before-first-heading: %S" (org-entry-get nil "IW_ESSAYS" nil) (org-before-first-heading-p))
    (message "doc props: %S" (seq-filter (lambda (p) (string-prefix-p "IW_" (car p))) (org-entry-properties nil 'standard)))
    (re-search-forward "^\\*\\* H1a") 
    (message "H1a local: %S inherit: %S" (org-entry-get nil "IW_ESSAYS" nil) (org-entry-get nil "IW_ESSAYS" t))
    (goto-char (point-min)) (re-search-forward "^\\* H2")
    (message "H2 id-create: %S modified: %S" (org-id-get-create) (buffer-modified-p))
    (org-entry-put nil "IW_ESSAYS" "6144")
    (message "H2 after put:\n%s" (buffer-substring (line-beginning-position -3) (point-max)))
    ;; scan all entries with an IW property: org-map-entries with match
    (message "map: %S" (org-map-entries (lambda () (cons (org-entry-get nil "ID") (org-entry-get nil "IW_ESSAYS"))) "IW_ESSAYS={.}" 'file))
    ;; case-insensitivity of property names
    (goto-char (point-min)) (re-search-forward "^\\* H1$")
    (message "lowercase get: %S" (org-entry-get nil "iw_essays"))
    ;; org-id-find across files
    (message "org-id-find h1: %S" (org-id-find "h1" 'marker))
    (set-buffer-modified-p nil)))
